### ISSUE TITLE
Prototype Design on GHA

### ISSUE THREAD

**Issue by emAmazed** [emAmazed/redlamp#39]
Some random thoughts on how to manage a clean and easier maintainable application that use vue.js as front, node.js with express as back, a shared common deployment process. It is a good practice for team management and access control. 

```
frontend-vue/
├── public/
│   └── index.html
├── src/
│   ├── assets/
│   ├── components/
│   ├── views/
│   ├── router/
│   │   └── index.js
│   ├── store/
│   │   └── index.js
│   └── main.js
├── .env
├── .gitignore
├── package.json
├── tests/
├── vite.config.js        # or vue.config.js if using Vue CLI
└── README.md
``` 

```
backend-node/
├── src/
│   ├── controllers/
│   ├── middleware/
│   ├── models/
│   ├── routes/
│   └── server.js
├── .env
├── .gitignore
├── Dockerfile
├── docker-compose.yml
├── package.json
└── README.md
```
* use /db/*, connects to a database (e.g. MongoDB/PostgreSQL), etc

```
infra-deployment/
├── terraform/
│   ├── main.tf
│   ├── variables.tf
│   ├── outputs.tf
│   ├── ec2.tf
│   └── security-groups.tf
├── docker/
│   ├── docker-compose.yml
│   └── nginx/
│       ├── default.conf
│       └── Dockerfile (if needed)
├── scripts/
│   ├── deploy.sh
│   └── init.sh
├── .gitignore
├── README.md
└── terraform.tfstate (gitignored)
```

* Uses tf to provision EC2, sg, IAM roles.
* docker-compose.yml to deploy both frontend and backend on the EC2.
* Keep .env files minimal in app repos; real config should come from secrets in CI/CD pipelines.

* flow: gha ci/cd used in each repo.
* EC2 runs Docker engine.infra-deployment repo cloned there to deploy everything.
* store Docker images in AWS ECR or build locally on EC2. question: dev env set-up?

* for multi-repo setup, copy the same workflow into each front/back repo, make sure each has the correct Dockerfile in the root or adjust the docker build path accordingly.

# example of .github/workflows/deploy.yml

```
name: Build and Push Docker Images to ECR

on:
  push:
    branches: [main]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_ACCOUNT_ID: ${{ secrets.ECR_ACCOUNT_ID }}
  FRONTEND_REPO: frontend-vue
  BACKEND_REPO: backend-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Optional: Build frontend
    - name: Build Frontend Docker Image
      if: ${{ github.repository == 'your-org/frontend-vue' }}
      run: |
        docker build -t $ECR_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPO:latest .
        docker push $ECR_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPO:latest

    # Optional: Build backend
    - name: Build Backend Docker Image
      if: ${{ github.repository == 'your-org/backend-api' }}
      run: |
        docker build -t $ECR_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPO:latest .
        docker push $ECR_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPO:latest

```

* use GitHub Webhooks or a simple CI runner on EC2 for atomated polling the latest ecr image
